In [1]:
%load_ext autoreload
%autoreload 2

# Leer los datos

In [2]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
def load_data(file_path):
    return pd.read_json(file_path, lines=True)

file_path = "../data/MLA_100k_checked_v3.jsonlines"
df = load_data(file_path)

print(df.dtypes)

df.head()

seller_address                              object
warranty                                    object
sub_status                                  object
condition                                   object
deal_ids                                    object
base_price                                 float64
shipping                                    object
non_mercado_pago_payment_methods            object
seller_id                                    int64
variations                                  object
site_id                                     object
listing_type_id                             object
price                                      float64
attributes                                  object
buying_mode                                 object
tags                                        object
listing_source                              object
parent_item_id                              object
coverage_areas                              object
category_id                                 object
descriptions                                object
last_updated                                object
international_delivery_mode                 object
pictures                                    object
id                                          object
official_store_id                          float64
differential_pricing                       float64
accepts_mercadopago                           bool
original_price                             float64
currency_id                                 object
thumbnail                                   object
title                                       object
automatic_relist                              bool
date_created                                object
secure_thumbnail                            object
stop_time                           datetime64[ns]
status                                      object
video_id                                    object
catalog_product_id                         float64
subtitle                                   float64
initial_quantity                             int64
start_time                          datetime64[ns]
permalink                                   object
sold_quantity                                int64
available_quantity                           int64
dtype: object

,seller_address,warranty,sub_status,condition,deal_ids,base_price,shipping,non_mercado_pago_payment_methods,seller_id,variations,...,stop_time,status,video_id,catalog_product_id,subtitle,initial_quantity,start_time,permalink,sold_quantity,available_quantity
0,"{'country': {'name': 'Argentina', 'id': 'AR'},...",None,[],new,[],80.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",8208882349,[],...,2015-11-04 20:42:53,active,None,NaN,NaN,1,2015-09-05 20:42:53,http://articulo.mercadolibre.com.ar/MLA4695330...,0,1
1,"{'country': {'name': 'Argentina', 'id': 'AR'},...",NUESTRA REPUTACION,[],used,[],2650.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",8141699488,[],...,2015-11-25 18:08:30,active,None,NaN,NaN,1,2015-09-26 18:08:30,http://articulo.mercadolibre.com.ar/MLA7160447...,0,1
2,"{'country': {'name': 'Argentina', 'id': 'AR'},...",None,[],used,[],60.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",8386096505,[],...,2015-11-08 23:57:07,active,None,NaN,NaN,1,2015-09-09 23:57:07,http://articulo.mercadolibre.com.ar/MLA7367189...,0,1
3,"{'country': {'name': 'Argentina', 'id': 'AR'},...",None,[],new,[],580.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",5377752182,[],...,2015-12-04 01:13:16,active,None,NaN,NaN,1,2015-09-28 18:47:56,http://articulo.mercadolibre.com.ar/MLA9191625...,0,1
4,"{'country': {'name': 'Argentina', 'id': 'AR'},...",MI REPUTACION.,[],used,[],30.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",2938071313,[],...,2015-10-23 22:07:20,active,None,NaN,NaN,1,2015-08-24 22:07:20,http://articulo.mercadolibre.com.ar/MLA7787961...,0,1